server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 129.204.105.83

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CN-Donily/config-center.git
          username: ld19950104@163.com
          password: DNFbanzhuan1995
